version: "3.9"

services:
  api:
    build:
      context: .              
      dockerfile: infra/Dockerfile
    image: dog-cat-api:latest 
    container_name: dog-cat-api
    environment:
      FLASK_ENV: production
      PORT: "5000"
      MODEL_PATH: /app/cat_dog_app/models
      DB_PATH: /app/data/results.sqlite
    ports:
      - "5000:5000"
    volumes:
    restart: unless-stopped
    command: >
      sh -c "python -u cat_dog_app/app.py"
